### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by iwr-redmond** [dunkeroni/InvokeAI_ModularDenoiseNodes#2]
InvokeAI version 5.3.0.
```
[2024-10-28 10:49:22,153]::[InvokeAI]::ERROR --> Failed to load node pack InvokeAI_ModularDenoiseNodes:
Traceback (most recent call last):
  File "/opt/invokeai/nodes/__init__.py", line 48, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/invokeai/nodes/InvokeAI_ModularDenoiseNodes/__init__.py", line 3, in <module>
    from .denoise_latents_nodes import (
  File "/opt/invokeai/nodes/InvokeAI_ModularDenoiseNodes/denoise_latents_nodes.py", line 30, in <module>
    from invokeai.backend.lora import LoRAModelRaw
ImportError: cannot import name 'LoRAModelRaw' from 'invokeai.backend.lora' (/opt/venvs/invokeai-5-3-0/lib/python3.10/site-packages/invokeai/backend/lora/__init__.py)
```

**Comment by iwr-redmond** [comment]
Here are the fixes required to load the modules, all in [denoise_latents_nodes.py](https://github.com/dunkeroni/InvokeAI_ModularDenoiseNodes/blob/main/denoise_latents_nodes.py):

```
30c30
< from invokeai.backend.lora import LoRAModelRaw
---
> from invokeai.backend.lora.lora_model_raw import LoRAModelRaw
32c32,33
< from invokeai.backend.stable_diffusion import PipelineIntermediateState, set_seamless
---
> from invokeai.backend.stable_diffusion import PipelineIntermediateState
> from invokeai.backend.stable_diffusion.extensions.seamless import SeamlessExt as set_seamless
```

**Comment by iwr-redmond** [comment]
Fixed with the restructure in [commit 918e8b2](https://github.com/dunkeroni/InvokeAI_ModularDenoiseNodes/commit/918e8b28611fd1e4627b153e2f4652c8a0323f0d). Thank you, sir!

**Comment by dunkeroni** [comment]
Fixed might be an overstatement. "Archived a bunch of features and haven't rewritten them yet" is a bit more accurate ;)
